Link to the official FreeBSD manual about BPF
zoidbergwill/awesome-ebpf pull request #37
Opened 2020-10-14 17:15 UTC by 0mp

The old link is dead anyway.

2020-10-14 17:37 UTC, qmonnet requested changes
Thanks for the contribution! Would you mind trimming the URL from the unnecessary bits, please?

2020-10-14 17:37 UTC, qmonnet commented on readme.md
> +- [The FreeBSD manual page about BPF](https://www.freebsd.org/cgi/man.cgi?query=bpf&sektion=&n=1)
```suggestion
- [The FreeBSD manual page about BPF](https://www.freebsd.org/cgi/man.cgi?query=bpf)
```

2020-10-16 13:24 UTC, 0mp commented
Great idea! I have actually specified the "sektion" in the URL now to 4 in order to be sure that the correct manual page is found.

2020-10-16 13:31 UTC, qmonnet approved these changes
Great, thank you!

2020-10-16 13:31 UTC, merged